### ISSUE TITLE
README diagram image is not accessible 

### ISSUE THREAD

**Issue by liamchampton** [Azure-Samples/function-call-dynamic-query-demo#5]
If people are using dark mode theme on GitHub it is hard to see / read the top level diagram.

<img width="1133" alt="Screenshot 2024-09-06 at 15 01 56" src="https://github.com/user-attachments/assets/32f28461-f50f-4cb0-8129-268ee96a4e13">

**Comment by abdulzedan** [comment]
thanks Liam, issue is resolved, will close the ticket now.
